### ISSUE TITLE
cv2 can not be installed successfully on Mac with M1 chip. The jupyter lab server.ipynb would stop running after the cell 'importing cv2'.

### ISSUE THREAD

**Issue by Jiezheng2018** [https-deeplearning-ai/MLEP-public#20]
The pip install of cvlib is successful with the conda environment method and the docker method. Both methods would fail when running import cvlib as cv. 

Running pip install TensorFlow then pip install cvlib in base python is successful, however, when importing cvlib, I get error "illegal hardware instruction  python" 

Is this because I am using Mac with an M1 chip?  Any help would be highly appreciated. 

Thanks a lot 

Jie

**Comment by andres-zartab** [comment]
Hi @Jiezheng2018, yes the issue seems to be caused by the M1 chip. Can you install TF 2.4.1 and try again? After some research it looks like this version is M1 compatible. If the error persists after that I would take a look at this resource (https://sayak.dev/install-opencv-m1/) on how to install openCV in M1 macs.

**Comment by Jiezheng2018** [comment]
Thank you very much for the fast response and for confirming the issue. I will try it in the next couple of days. 
Thanks a lot.
